pipeline:
  composer:
    image: composer
    commands:
      - composer install

  code-style:
    image: php:7.1-cli-alpine
    commands:
      - php vendor/bin/php-cs-fixer fix --dry-run --diff
      - php vendor/bin/phpstan analyse -c phpstan.neon -l 2 bin config src

  build-phar:
    image: patrickjahns/box
    commands:
      - box compile --config box.json
    when:
      event: [push, pull_request]

  build-signed-phar:
    image: patrickjahns/box
    secrets: [signing_key]
    commands:
      - mkdir .keys
      - echo "$${SIGNING_KEY}" > .keys/phar-private.pem
      - box compile --config box.json.dist
    when:
      event: tag

  verify-build:
    image: patrickjahns/box
    commands:
      - box verify ./build/cliph.phar

  acceptance-test:
    image: php:7.1-cli-alpine
    commands:
      - cd build
      - ./cliph.phar hello

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: build/*
    checksum: sha256
    when:
      event: tag



