pipeline:
  restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false
      event: [push, pull_request]

  composer:
    image: owncloudci/php:7.1
    pull: true
    commands:
      - composer install

  rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - vendor
      - vendor-bin
    when:
      local: false
      event: [push]
      branch: master

  flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [push]
      branch: master

  code-style:
    image: owncloudci/php:7.1
    pull: true
    commands:
      - php vendor/bin/php-cs-fixer fix --dry-run --diff

  static-code-analyzer-71:
    image: owncloudci/php:7.1
    pull: true
    group: static-code-analyzer
    commands:
      - php vendor/bin/phpstan analyse -c phpstan.neon -l 4 bin config src
      - php ./vendor/bin/psalm
      - php vendor/bin/phan

  static-code-analyzer-72:
    image: owncloudci/php:7.2
    pull: true
    group: static-code-analyzer
    commands:
      - php vendor/bin/phpstan analyse -c phpstan.neon -l 4 bin config src
      - php ./vendor/bin/psalm
      - php vendor/bin/phan

  phpunit:
    image: owncloudci/php:7.1
    pull: true
    commands:
      - php vendor/bin/phpunit

  composer-prepare-build:
    image: owncloudci/php:7.1
    pull: true
    commands:
      - composer install --no-dev --no-plugins --no-scripts --optimize-autoloader --classmap-authoritative

  build-phar:
    image: patrickjahns/box
    pull: true
    commands:
      - box compile --config box.json
    when:
      event: [push, pull_request]

  build-signed-phar:
    image: patrickjahns/box
    pull: true
    secrets: [signing_key]
    commands:
      - mkdir .keys
      - echo "$${SIGNING_KEY}" > .keys/phar-private.pem
      - box compile --config box.json.dist
    when:
      event: tag

  verify-build:
    image: patrickjahns/box
    pull: true
    commands:
      - box verify ./build/cliph.phar

  acceptance-test:
    image: php:7.1-cli-alpine
    pull: true
    commands:
      - cd build
      - ./cliph.phar hello

  github_release:
    image: plugins/github-release
    pull: true
    secrets: [ github_token ]
    files: build/*
    checksum: sha256
    when:
      event: tag



