services:
  _defaults:
   autowire: true
   autoconfigure: true

  OC\Tekton\Console\Application:
    public: true
    arguments: ['@Symfony\Component\DependencyInjection\ContainerInterface']


  console_commands:
    namespace: OC\Tekton\Console\Command\
    resource: '../src/Console/Command/*'
    tags: ['console.command']
    public: true