services:
  _defaults:
   autowire: true
   autoconfigure: true

  Cliph\Console\Application:
    public: true

  Cliph\Console\Command\HelloWorldCommand:
    public: true
    tags: ['console.command']