services:
  _defaults:
   autowire: true
   autoconfigure: true

  Cliph\Console\Application:
    public: true
    arguments: ['@Symfony\Component\DependencyInjection\ContainerInterface']


  console_commands:
    namespace: Cliph\Console\Command\
    resource: '../src/Console/Command/*'
    tags: ['console.command']
    public: true