services:
  _defaults:
   autowire: true
   autoconfigure: true

  Cliph\Console\Application:
    public: true

  console_commands:
    namespace: Cliph\Console\Command\
    resource: '../src/Console/Command/*'
    tags: ['console.command']